import 'package:payout/features/transactions/models/transaction_models.dart';

class DummyTransactionData {
  static final List<TransactionModel> dummyTransactions = [
    const TransactionModel(
      id: 'TXN-901',
      title: 'Starbucks Coffee',
      upiId: 'starbucks@okaxis',
      type: 'DEBIT',
      category: 'Food & Beverage',
      amount: 320.00,
      date: 'Today, 1:45 PM',
      status: 'SUCCESS',
      paymentMethod: 'UPI VPA',
      utr: 'UTR789230198273',
      referenceNumber: 'REF9081230981',
    ),
    const TransactionModel(
      id: 'TXN-902',
      title: 'Domino\'s Pizza',
      upiId: 'dominos@okhdfcbank',
      type: 'DEBIT',
      category: 'Food & Beverage',
      amount: 680.00,
      date: 'Yesterday, 8:20 PM',
      status: 'SUCCESS',
      paymentMethod: 'Payout Wallet',
      utr: 'UTR789230198274',
      referenceNumber: 'REF9081230982',
    ),
    const TransactionModel(
      id: 'TXN-903',
      title: 'Reliance Fresh',
      upiId: 'reliancefresh@okicici',
      type: 'DEBIT',
      category: 'Grocery',
      amount: 1240.00,
      date: 'Yesterday, 11:30 AM',
      status: 'SUCCESS',
      paymentMethod: 'Bank Account',
      utr: 'UTR789230198275',
      referenceNumber: 'REF9081230983',
    ),
    const TransactionModel(
      id: 'TXN-904',
      title: 'Electricity Bill',
      upiId: 'bescom@okaxis',
      type: 'DEBIT',
      category: 'Electricity Bill',
      amount: 3200.00,
      date: 'This Week, Monday',
      status: 'SUCCESS',
      paymentMethod: 'Bank Account',
      utr: 'UTR789230198276',
      referenceNumber: 'REF9081230984',
    ),
    const TransactionModel(
      id: 'TXN-905',
      title: 'FASTag Recharge',
      upiId: 'netc.fastag@okaxis',
      type: 'DEBIT',
      category: 'FASTag Recharge',
      amount: 500.00,
      date: 'This Week, Sunday',
      status: 'SUCCESS',
      paymentMethod: 'Payout Wallet',
      utr: 'UTR789230198277',
      referenceNumber: 'REF9081230985',
    ),
    const TransactionModel(
      id: 'TXN-906',
      title: 'Cashback Received',
      upiId: 'rewards@payout',
      type: 'CREDIT',
      category: 'Cashback',
      amount: 50.00,
      date: 'Earlier, 5 Days Ago',
      status: 'SUCCESS',
      paymentMethod: 'Payout Wallet',
      utr: 'UTR789230198278',
      referenceNumber: 'REF9081230986',
    ),
    const TransactionModel(
      id: 'TXN-907',
      title: 'Refund AXIS Bank',
      upiId: 'axisbank@okaxis',
      type: 'CREDIT',
      category: 'Refund',
      amount: 1500.00,
      date: 'Earlier, 1 Week Ago',
      status: 'SUCCESS',
      paymentMethod: 'Bank Account',
      utr: 'UTR789230198279',
      referenceNumber: 'REF9081230987',
    ),
  ];
}
