// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAebQU_SDQZ3YUF6RF30EC5XHxMIkn_G0s',
    appId: '1:999007577431:web:0d78159b0124cd1fca4a12',
    messagingSenderId: '999007577431',
    projectId: 'payout-904f9',
    authDomain: 'payout-904f9.firebaseapp.com',
    storageBucket: 'payout-904f9.firebasestorage.app',
    measurementId: 'G-D4J5GXKBHV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwFGYkWivrV6qVoAoNb5PMukFzgdIoPHE',
    appId: '1:999007577431:android:1b5b65903d3842ebca4a12',
    messagingSenderId: '999007577431',
    projectId: 'payout-904f9',
    storageBucket: 'payout-904f9.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCediEEz77N3oaHGs7U-MEI2QQ9AcHDa3o',
    appId: '1:999007577431:ios:7a9ce98efabfd362ca4a12',
    messagingSenderId: '999007577431',
    projectId: 'payout-904f9',
    storageBucket: 'payout-904f9.firebasestorage.app',
    iosBundleId: 'com.example.payout',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCediEEz77N3oaHGs7U-MEI2QQ9AcHDa3o',
    appId: '1:999007577431:ios:7a9ce98efabfd362ca4a12',
    messagingSenderId: '999007577431',
    projectId: 'payout-904f9',
    storageBucket: 'payout-904f9.firebasestorage.app',
    iosBundleId: 'com.example.payout',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAebQU_SDQZ3YUF6RF30EC5XHxMIkn_G0s',
    appId: '1:999007577431:web:853a2071787d76c7ca4a12',
    messagingSenderId: '999007577431',
    projectId: 'payout-904f9',
    authDomain: 'payout-904f9.firebaseapp.com',
    storageBucket: 'payout-904f9.firebasestorage.app',
    measurementId: 'G-2FPJZ4X4PF',
  );
}
