import 'package:payout/features/recharge/models/recharge_models.dart';

class DummyRechargeData {
  static final List<OperatorModel> dummyOperators = [
    const OperatorModel(name: 'Jio', logoUrl: ''),
    const OperatorModel(name: 'Airtel', logoUrl: ''),
    const OperatorModel(name: 'Vi', logoUrl: ''),
    const OperatorModel(name: 'BSNL', logoUrl: ''),
  ];

  static final List<RechargePlanModel> dummyPlans = [
    // Jio plans
    const RechargePlanModel(
      id: 'JIO-POP-299',
      amount: 299.00,
      validity: '28 Days',
      data: '1.5 GB/Day',
      description: 'Unlimited high speed internet and voice calls.',
      category: 'Popular',
      operator: 'Jio',
      calls: 'Unlimited',
      sms: '100 SMS/Day',
    ),
    const RechargePlanModel(
      id: 'JIO-UNL-719',
      amount: 719.00,
      validity: '84 Days',
      data: '2.0 GB/Day',
      description: 'Super value pack. Includes Jio Apps access.',
      category: 'Unlimited',
      operator: 'Jio',
      calls: 'Unlimited',
      sms: '100 SMS/Day',
    ),
    const RechargePlanModel(
      id: 'JIO-DATA-19',
      amount: 19.00,
      validity: 'Active Plan',
      data: '1.0 GB Total',
      description: 'High speed data booster.',
      category: 'Data',
      operator: 'Jio',
      calls: 'N/A',
      sms: 'N/A',
    ),
    const RechargePlanModel(
      id: 'JIO-VAL-395',
      amount: 395.00,
      validity: '84 Days',
      data: '6.0 GB Total',
      description: 'Long validity budget pack.',
      category: 'Validity',
      operator: 'Jio',
      calls: 'Unlimited',
      sms: '1000 SMS Total',
    ),
    const RechargePlanModel(
      id: 'JIO-TT-100',
      amount: 100.00,
      validity: 'Unlimited',
      data: '0 GB',
      description: 'Talktime benefit of ₹81.75.',
      category: 'Talktime',
      operator: 'Jio',
      calls: 'N/A',
      sms: 'N/A',
    ),
    const RechargePlanModel(
      id: 'JIO-SMS-179',
      amount: 179.00,
      validity: '24 Days',
      data: '1.0 GB Total',
      description: 'Pack for users needing SMS and basic usage.',
      category: 'SMS',
      operator: 'Jio',
      calls: 'Unlimited',
      sms: '100 SMS/Day',
    ),

    // Airtel plans
    const RechargePlanModel(
      id: 'ART-POP-319',
      amount: 319.00,
      validity: '1 Month',
      data: '2.0 GB/Day',
      description: 'Unlimited calling & Wynk Music free.',
      category: 'Popular',
      operator: 'Airtel',
      calls: 'Unlimited',
      sms: '100 SMS/Day',
    ),
    const RechargePlanModel(
      id: 'ART-UNL-839',
      amount: 839.00,
      validity: '84 Days',
      data: '2.0 GB/Day',
      description: 'Airtel Xstream Play subscription included.',
      category: 'Unlimited',
      operator: 'Airtel',
      calls: 'Unlimited',
      sms: '100 SMS/Day',
    ),
    const RechargePlanModel(
      id: 'ART-DATA-58',
      amount: 58.00,
      validity: 'Active Plan',
      data: '3.0 GB Total',
      description: 'High speed data booster.',
      category: 'Data',
      operator: 'Airtel',
      calls: 'N/A',
      sms: 'N/A',
    ),
    const RechargePlanModel(
      id: 'ART-VAL-455',
      amount: 455.00,
      validity: '84 Days',
      data: '6.0 GB Total',
      description: 'Long validity calling pack.',
      category: 'Validity',
      operator: 'Airtel',
      calls: 'Unlimited',
      sms: '900 SMS Total',
    ),
    const RechargePlanModel(
      id: 'ART-TT-50',
      amount: 50.00,
      validity: 'Unlimited',
      data: '0 GB',
      description: 'Talktime benefit of ₹39.37.',
      category: 'Talktime',
      operator: 'Airtel',
      calls: 'N/A',
      sms: 'N/A',
    ),
    const RechargePlanModel(
      id: 'ART-SMS-155',
      amount: 155.00,
      validity: '24 Days',
      data: '1.0 GB Total',
      description: 'Basic calling & SMS pack.',
      category: 'SMS',
      operator: 'Airtel',
      calls: 'Unlimited',
      sms: '300 SMS Total',
    ),

    // BSNL plans
    const RechargePlanModel(
      id: 'BSN-POP-107',
      amount: 107.00,
      validity: '35 Days',
      data: '3.0 GB Total',
      description: 'Popular BSNL budget plan.',
      category: 'Popular',
      operator: 'BSNL',
      calls: '200 Mins',
      sms: 'N/A',
    ),
    // Vi plans
    const RechargePlanModel(
      id: 'VI-POP-299',
      amount: 299.00,
      validity: '28 Days',
      data: '1.5 GB/Day',
      description: 'Hero Unlimited night data benefit.',
      category: 'Popular',
      operator: 'Vi',
      calls: 'Unlimited',
      sms: '100 SMS/Day',
    ),
  ];

  static final List<RecentRechargeModel> dummyRecents = [
    const RecentRechargeModel(
      id: 'REC-301',
      mobileNumber: '9876543210',
      operatorName: 'Jio',
      amount: 299.0,
      date: 'Today, 2:30 PM',
    ),
    const RecentRechargeModel(
      id: 'REC-302',
      mobileNumber: '8765432109',
      operatorName: 'Airtel',
      amount: 719.0,
      date: 'Yesterday',
    ),
  ];
}
