import 'package:payout/features/financial/shared/models/financial_models.dart';

class DummyFinancialData {
  static final List<LoanModel> dummyLoans = [
    const LoanModel(
      id: 'LON-101',
      title: 'Instant Personal Loan',
      category: 'Personal',
      interestRate: 10.5,
      tenureMonths: 36,
      minAmount: 10000.0,
      maxAmount: 500000.0,
      minTenureMonths: 6,
      maxTenureMonths: 60,
      processingFeePercent: 1.5,
      approvalTime: 'Instant in 2 minutes',
      benefits: ['Instant bank credit', 'No physical documents', 'Flexible tenure up to 5 years'],
    ),
    const LoanModel(
      id: 'LON-102',
      title: 'MSME Business Growth Loan',
      category: 'Business',
      interestRate: 11.75,
      tenureMonths: 48,
      minAmount: 50000.0,
      maxAmount: 2000000.0,
      minTenureMonths: 12,
      maxTenureMonths: 60,
      processingFeePercent: 2.0,
      approvalTime: '24-48 Hours',
      benefits: ['High loan limits up to ₹20 Lakhs', 'Collateral free', 'Tax benefits on interest'],
    ),
    const LoanModel(
      id: 'LON-103',
      title: 'Higher Studies Education Loan',
      category: 'Education',
      interestRate: 8.95,
      tenureMonths: 60,
      minAmount: 100000.0,
      maxAmount: 1500000.0,
      minTenureMonths: 12,
      maxTenureMonths: 84,
      processingFeePercent: 1.0,
      approvalTime: '1-3 Business Days',
      benefits: ['Subsidised student rates', 'Moratorium period available', '100% course fee covered'],
    ),
    const LoanModel(
      id: 'LON-104',
      title: 'Emergency Medical & Cash Credit',
      category: 'Emergency',
      interestRate: 12.5,
      tenureMonths: 24,
      minAmount: 5000.0,
      maxAmount: 100000.0,
      minTenureMonths: 3,
      maxTenureMonths: 24,
      processingFeePercent: 1.0,
      approvalTime: 'Instant in 60 seconds',
      benefits: ['24/7 instant cash disbursal', 'Zero pre-closure penalty', 'Minimal documentation'],
    ),
  ];

  static final List<InsurancePolicyModel> dummyPolicies = [
    const InsurancePolicyModel(
      id: 'INS-201',
      providerName: 'Care Health Insurance',
      name: 'Care Health Shield Max',
      type: 'Health',
      premium: 450.0,
      coverage: 500000.0,
      duration: '1 Year',
      claimSettlementRatio: 98.6,
      benefits: ['Cashless at 10,000+ hospitals', 'No room rent cap', 'Annual health checkup included'],
    ),
    const InsurancePolicyModel(
      id: 'INS-202',
      providerName: 'ICICI Prudential Life',
      name: 'ICICI Pru iProtect Smart',
      type: 'Life',
      premium: 650.0,
      coverage: 10000000.0,
      duration: '1 Year (Renewable)',
      claimSettlementRatio: 99.1,
      benefits: ['₹1 Crore term life cover', 'Terminal illness cover', 'Tax exemption under Sec 80C'],
    ),
    const InsurancePolicyModel(
      id: 'INS-203',
      providerName: 'HDFC ERGO General Insurance',
      name: 'HDFC Ergo Comprehensive Motor Shield',
      type: 'Motor',
      premium: 380.0,
      coverage: 350000.0,
      duration: '1 Year',
      claimSettlementRatio: 97.8,
      benefits: ['Zero depreciation add-on', '24/7 roadside assistance', 'Quick cashless garage repair'],
    ),
    const InsurancePolicyModel(
      id: 'INS-204',
      providerName: 'Tata AIG General Insurance',
      name: 'Tata AIG Global Travel Protect',
      type: 'Travel',
      premium: 299.0,
      coverage: 2500000.0,
      duration: 'Per Trip / 30 Days',
      claimSettlementRatio: 98.2,
      benefits: ['Medical emergency cover abroad', 'Baggage loss / delay protection', 'Flight cancellation cover'],
    ),
  ];

  static final List<InvestmentModel> dummyInvestments = [
    const InvestmentModel(
      id: 'INV-301',
      fundName: 'Nippon India Large Cap Fund',
      category: 'Large Cap',
      type: 'Mutual Fund',
      nav: 78.40,
      returnPercentage: 15.6,
      riskLevel: 'Moderate',
      minInvestment: 500.0,
      minSip: 500.0,
      expenseRatio: 0.78,
      description: 'Invests in top 100 bluechip companies across India with stable, long-term returns.',
    ),
    const InvestmentModel(
      id: 'INV-302',
      fundName: 'Quant Small Cap Dynamic Growth',
      category: 'Small Cap',
      type: 'Mutual Fund',
      nav: 145.20,
      returnPercentage: 22.8,
      riskLevel: 'Very High',
      minInvestment: 1000.0,
      minSip: 1000.0,
      expenseRatio: 0.95,
      description: 'High-growth small cap fund aiming for aggressive alpha generation in emerging market leaders.',
    ),
    const InvestmentModel(
      id: 'INV-303',
      fundName: 'Payout 24K 99.9% Pure Digital Gold',
      category: 'Gold',
      type: 'Digital Gold',
      nav: 72.50,
      returnPercentage: 12.4,
      riskLevel: 'Low',
      minInvestment: 100.0,
      minSip: 500.0,
      expenseRatio: 0.0,
      exitLoad: 'Zero exit load',
      description: '100% insured physical gold stored in world-class Brink’s vaults with instant liquidity.',
    ),
    const InvestmentModel(
      id: 'INV-304',
      fundName: 'HDFC Corporate Bond Debt Fund',
      category: 'Debt',
      type: 'Fixed Income',
      nav: 26.80,
      returnPercentage: 7.9,
      riskLevel: 'Low',
      minInvestment: 500.0,
      minSip: 500.0,
      expenseRatio: 0.45,
      exitLoad: 'Zero exit load after 30 days',
      description: 'Invests in AAA-rated high-grade corporate bonds for capital protection and consistent income.',
    ),
  ];

  static PortfolioModel dummyPortfolio = PortfolioModel(
    totalInvested: 107000.00,
    currentValue: 125450.00,
    returnsValue: 18450.00,
    returnPercentage: 17.24,
    holdings: [
      const PortfolioHoldingModel(
        id: 'HLD-001',
        fundId: 'INV-301',
        fundName: 'Nippon India Large Cap Fund',
        category: 'Large Cap',
        investedAmount: 50000.00,
        currentValue: 58500.00,
        returnsValue: 8500.00,
        returnPercentage: 17.0,
        investmentDate: '15 Jan 2024',
      ),
      const PortfolioHoldingModel(
        id: 'HLD-002',
        fundId: 'INV-303',
        fundName: 'Payout 24K Pure Digital Gold',
        category: 'Gold',
        investedAmount: 57000.00,
        currentValue: 66950.00,
        returnsValue: 9950.00,
        returnPercentage: 17.45,
        investmentDate: '02 Feb 2024',
      ),
    ],
  );
}
